# Generated by Django 6.0.7 on 2026-07-30 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_bio_user_company_name_user_county_user_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='verification/id_front/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='verification/id_back/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='verification/selfie/')),
                ('kra_pin', models.FileField(blank=True, null=True, upload_to='verification/kra/')),
                ('business_certificate', models.FileField(blank=True, null=True, upload_to='verification/business/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
