# Generated by Django 6.0.7 on 2026-08-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_online_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
