# Generated by Django 6.0.7 on 2026-08-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_address_user_alternative_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
