# Generated by Django 6.0.7 on 2026-09-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_alternate_phone_user_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='kra_api_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='kra_obligation_status',
            field=models.CharField(choices=[('NOT_CHECKED', 'Not Checked'), ('FOUND', 'Found'), ('NOT_FOUND', 'Not Found'), ('UNKNOWN', 'Unknown'), ('MANUAL_REVIEW', 'Manual Review')], default='NOT_CHECKED', max_length=30),
        ),
        migrations.AddField(
            model_name='userverification',
            name='kra_verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='kra_verification_status',
            field=models.CharField(choices=[('NOT_CHECKED', 'Not Checked'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('MANUAL_REVIEW', 'Manual Review')], default='NOT_CHECKED', max_length=30),
        ),
        migrations.AddField(
            model_name='userverification',
            name='kra_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
