# Generated by Django 6.0.7 on 2026-08-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CHAT', 'Chat'), ('BOOKING', 'Booking'), ('PAYMENT', 'Payment'), ('PROPERTY', 'Property'), ('VERIFICATION', 'Verification'), ('SECURITY', 'Security'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
