# Generated by Django 6.0.7 on 2026-07-29 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_google_maps_url_property_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('RENTED', 'Rented')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INSTITUTIONAL', 'Institutional'), ('LAND', 'Land')], default='RESIDENTIAL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('FURNISHED', 'Furnished'), ('SEMI_FURNISHED', 'Semi Furnished'), ('UNFURNISHED', 'Unfurnished')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('RENT', 'For Rent'), ('SALE', 'For Sale')], default='RESIDENTIAL', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('SINGLE_ROOM', 'Single Room'), ('BEDSITTER', 'Bedsitter'), ('STUDIO', 'Studio Apartment'), ('ONE_BEDROOM', 'One Bedroom'), ('TWO_BEDROOM', 'Two Bedroom'), ('THREE_BEDROOM', 'Three Bedroom'), ('FOUR_BEDROOM', 'Four Bedroom'), ('APARTMENT', 'Apartment'), ('MAISONETTE', 'Maisonette'), ('BUNGALOW', 'Bungalow'), ('VILLA', 'Villa'), ('SHOP', 'Shop'), ('OFFICE', 'Office'), ('WAREHOUSE', 'Warehouse'), ('GODOWN', 'Godown'), ('HOTEL', 'Hotel'), ('LODGE', 'Lodge'), ('RESTAURANT', 'Restaurant'), ('INDUSTRIAL', 'Industrial Building'), ('LAND', 'Land'), ('RESIDENTIAL_PLOT', 'Residential Plot'), ('COMMERCIAL_PLOT', 'Commercial Plot'), ('AGRICULTURAL_LAND', 'Agricultural Land'), ('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('CHURCH', 'Church'), ('MOSQUE', 'Mosque')], max_length=30),
        ),
    ]
