# Generated by Django 6.0.7 on 2026-07-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_agent_property_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INSTITUTIONAL', 'Institutional'), ('LAND', 'Land')], default='RESIDENTIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('RENT', 'For Rent'), ('SALE', 'For Sale')], default='RENT', max_length=10),
        ),
    ]
