# Generated by Django 6.0.7 on 2026-08-03 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_category_alter_property_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDailyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('favourites', models.PositiveIntegerField(default=0)),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('chats', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='properties.property')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('property', 'date')},
            },
        ),
    ]
