# Generated by Django 6.0.7 on 2026-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceprovider_primary_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='license_number',
            field=models.CharField(blank=True, help_text='Optional professional or business license number.', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='qualification',
            field=models.TextField(blank=True, help_text='Relevant training, certifications, or professional qualifications.'),
        ),
    ]
