# Generated by Django 6.0.7 on 2026-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
