# Generated by Django 6.0.7 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_payments', '0002_alter_rentpayment_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
