# Generated by Django 6.0.7 on 2026-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_alter_lease_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='agreement_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='agreement_status',
            field=models.CharField(choices=[('PENDING', 'Pending Signatures'), ('PARTIALLY_SIGNED', 'Partially Signed'), ('SIGNED', 'Fully Signed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='landlord_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='verification_id',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True),
        ),
    ]
