# Generated by Django 6.0.7 on 2026-08-07 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('place_type', models.CharField(choices=[('SCHOOL', 'School'), ('HOSPITAL', 'Hospital'), ('SUPERMARKET', 'Supermarket'), ('POLICE', 'Police Station'), ('CHURCH', 'Church'), ('MOSQUE', 'Mosque'), ('BUS_STAGE', 'Bus Stage'), ('RESTAURANT', 'Restaurant'), ('BANK', 'Bank'), ('PHARMACY', 'Pharmacy')], max_length=30)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('source', models.CharField(default='GOOGLE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['distance_km', 'name'],
            },
        ),
    ]
